[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kiauh"
version = "0.0.0"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["ruff", "mypy", "pytest", "pytest-cov"]

[tool.ruff]
required-version = ">=0.9.10"
respect-gitignore = true
exclude = [".git", ".github", "./docs"]
line-length = 88
indent-width = 4
output-format = "full"
target-version = "py38"

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
python_version = "3.8"
platform = "linux"
explicit_package_bases = true
mypy_path = "kiauh"
check_untyped_defs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

[tool.coverage.report]
fail_under = 65
skip_covered = false

[tool.pytest.ini_options]
minversion = "8.2.1"
testpaths = [
    "kiauh/components/klipper/services/tests",
    "kiauh/components/moonraker/services/tests",
    "kiauh/components/moonraker/utils/tests",
    "kiauh/components/webui_client/services/tests",
    "kiauh/components/webui_client/tests",
    "kiauh/components/webui_client/menus/tests",
    "kiauh/core/backends/tests",
    "kiauh/core/cli/tests",
    "kiauh/core/instance_manager/tests",
    "kiauh/core/menus/tests",
    "kiauh/core/services/tests",
    "kiauh/core/tests",
    "kiauh/core/settings/tests",
    "kiauh/core/simple_config_parser/tests",
    "kiauh/extensions/https/tests",
    "kiauh/extensions/tests",
    "kiauh/tests",
    "kiauh/utils/tests",
]
pythonpath = ["kiauh"]
